name: Deploy Docker Image

on:
  push:
    branches: [dev]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Authentication
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Image
      working-directory: ./docker/inep_ingestion
      env:
        DOCKER_IMAGE: python-container
      run: docker build -t $DOCKER_IMAGE:latest .
    
    - name: Tag and Push Docker Image
      env:
        DOCKER_IMAGE: python-container
        IMAGE_TAG: latest
      run: |
        docker tag $DOCKER_IMAGE:latest ${{secrets.DOCKER_USER}}/$DOCKER_IMAGE:$IMAGE_TAG
        docker push ${{secrets.DOCKER_USER}}/$DOCKER_IMAGE:$IMAGE_TAG